<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AuthorizationServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AuthorizationServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AuthorizationServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://service.onlinebookstore.com/">
    <import location="AuthorizationService.wsdl" namespace="http://service.onlinebookstore.com/"/>
    <plnk:partnerLinkType name="AuthorizationLinkType">
        <plnk:role name="AuthorizationRole" portType="ns:Authorization"/>
    </plnk:partnerLinkType>
</definitions>
