//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.11 at 12:00:25 fm CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Transcripts")
package hw1.jaxb.transcripts;
