//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.10 at 11:33:50 em CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/ApplicantProfile")
package hw1.jaxb.applicantProfile;
