//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.14 at 09:27:50 em CET 
//


package hw1.jaxb.applicantProfile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for companyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="companyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="positionorTitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lengthofTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "companyType", namespace = "http://www.example.org/EmploymentRecord", propOrder = {
    "name",
    "positionorTitle",
    "lengthofTime"
})
@XmlSeeAlso({
    WorkType.class
})
public class CompanyType {

    @XmlElement(namespace = "http://www.example.org/EmploymentRecord", required = true)
    protected String name;
    @XmlElement(namespace = "http://www.example.org/EmploymentRecord", required = true)
    protected String positionorTitle;
    @XmlElement(namespace = "http://www.example.org/EmploymentRecord", required = true)
    protected String lengthofTime;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the positionorTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPositionorTitle() {
        return positionorTitle;
    }

    /**
     * Sets the value of the positionorTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPositionorTitle(String value) {
        this.positionorTitle = value;
    }

    /**
     * Gets the value of the lengthofTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthofTime() {
        return lengthofTime;
    }

    /**
     * Sets the value of the lengthofTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthofTime(String value) {
        this.lengthofTime = value;
    }

}
