/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CustomerCart.java
 *
 * Created on 2010-3-9, 22:15:38
 */

package eLUX;

import com.elux.ado.order.OrderItem;
import com.elux.system.webcustsys.IWebCustSys;
import java.util.Vector;
import javax.swing.DefaultListModel;

/**
 *
 * @author binbin
 */
public class CustomerCart extends javax.swing.JDialog {

    Vector<OrderItem> itemList = new Vector<OrderItem>();
    private IWebCustSys cusSys;
    private int customerID =0;

    /** Creates new form CustomerCart */
    public CustomerCart(java.awt.Frame parent, boolean modal, IWebCustSys customerSys, int cusID) {
        super(parent, modal);
        initComponents();
        addToList();
        cusSys = customerSys;
        customerID = cusID;
    }
    public CustomerCart(OrderItem item){
        itemList.addElement(item);
    }

    private void addToList(){
        DefaultListModel list = new DefaultListModel();
        for(OrderItem ordList: itemList) {
            list.addElement(ordList.getProID() + "- Ordered Amount: " + ordList.getOrdItermAmount());
        }
        listOrder.setModel(list);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listOrder = new javax.swing.JList();
        btnOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Cart");

        listOrder.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listOrder);

        btnOrder.setText("Confirm Order");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnOrder)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addComponent(btnOrder))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        cusSys.sendOrder(customerID, itemList);
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listOrder;
    // End of variables declaration//GEN-END:variables

}
