<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WizardCorrelationProperties.wsdl" targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties" xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:ns0="http://xml.netbeans.org/schema/BookStore" xmlns:ns="http://j2ee.netbeans.org/wsdl/OrderBook" xmlns:tns="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
    <import namespace="http://j2ee.netbeans.org/wsdl/OrderBook" location="Partners/OrderBook.wsdl"/>
    <types>
        <xsd:schema targetNamespace="http://enterprise.netbeans.org/bpel/WizardCorrelationProperties">
            <xsd:import namespace="http://xml.netbeans.org/schema/BookStore" schemaLocation="Partners/BookStore.xsd"/>
        </xsd:schema>
    </types>
    <vprop:property name="wzrd_prop_title_title" type="xsd:string"/>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_title_title" messageType="ns:OrderBookOperationRequest" part="input">
        <vprop:query>/ns0:orderBookRequest/ns0:title</vprop:query>
    </vprop:propertyAlias>
    <vprop:propertyAlias propertyName="tns:wzrd_prop_title_title" messageType="ns:OrderBookOperationResponse" part="input">
        <vprop:query>/ns0:orderBookResponse/ns0:return/ns0:book/ns0:title</vprop:query>
    </vprop:propertyAlias>
</definitions>
