//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.11 at 02:10:08 ÉÏÎç CET 
//


package hw1.jaxb.applicantProfile;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hw1.jaxb.applicantProfile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ApplicantProfile_QNAME = new QName("http://www.example.org/ApplicantProfile", "applicantProfile");
    private final static QName _ShortCV_QNAME = new QName("http://www.example.org/ShortCV", "shortCV");
    private final static QName _Companies_QNAME = new QName("http://www.example.org/CompanyInfo", "Companies");
    private final static QName _Transcripts_QNAME = new QName("http://www.example.org/Transcripts", "transcripts");
    private final static QName _EmploymentRecord_QNAME = new QName("http://www.example.org/EmploymentRecord", "employmentRecord");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hw1.jaxb.applicantProfile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecordType }
     * 
     */
    public RecordType createRecordType() {
        return new RecordType();
    }

    /**
     * Create an instance of {@link EducationType }
     * 
     */
    public EducationType createEducationType() {
        return new EducationType();
    }

    /**
     * Create an instance of {@link PersonalInfoType }
     * 
     */
    public PersonalInfoType createPersonalInfoType() {
        return new PersonalInfoType();
    }

    /**
     * Create an instance of {@link TranscriptType }
     * 
     */
    public TranscriptType createTranscriptType() {
        return new TranscriptType();
    }

    /**
     * Create an instance of {@link InfoType }
     * 
     */
    public InfoType createInfoType() {
        return new InfoType();
    }

    /**
     * Create an instance of {@link CompaniesType }
     * 
     */
    public CompaniesType createCompaniesType() {
        return new CompaniesType();
    }

    /**
     * Create an instance of {@link CoursesType }
     * 
     */
    public CoursesType createCoursesType() {
        return new CoursesType();
    }

    /**
     * Create an instance of {@link TranscriptsType }
     * 
     */
    public TranscriptsType createTranscriptsType() {
        return new TranscriptsType();
    }

    /**
     * Create an instance of {@link EducationItemType }
     * 
     */
    public EducationItemType createEducationItemType() {
        return new EducationItemType();
    }

    /**
     * Create an instance of {@link ApplicantProfileType }
     * 
     */
    public ApplicantProfileType createApplicantProfileType() {
        return new ApplicantProfileType();
    }

    /**
     * Create an instance of {@link WorkExperienceType }
     * 
     */
    public WorkExperienceType createWorkExperienceType() {
        return new WorkExperienceType();
    }

    /**
     * Create an instance of {@link WorkType }
     * 
     */
    public WorkType createWorkType() {
        return new WorkType();
    }

    /**
     * Create an instance of {@link CompanyType }
     * 
     */
    public CompanyType createCompanyType() {
        return new CompanyType();
    }

    /**
     * Create an instance of {@link CvType }
     * 
     */
    public CvType createCvType() {
        return new CvType();
    }

    /**
     * Create an instance of {@link CourseType }
     * 
     */
    public CourseType createCourseType() {
        return new CourseType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicantProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/ApplicantProfile", name = "applicantProfile")
    public JAXBElement<ApplicantProfileType> createApplicantProfile(ApplicantProfileType value) {
        return new JAXBElement<ApplicantProfileType>(_ApplicantProfile_QNAME, ApplicantProfileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CvType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/ShortCV", name = "shortCV")
    public JAXBElement<CvType> createShortCV(CvType value) {
        return new JAXBElement<CvType>(_ShortCV_QNAME, CvType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/CompanyInfo", name = "Companies")
    public JAXBElement<InfoType> createCompanies(InfoType value) {
        return new JAXBElement<InfoType>(_Companies_QNAME, InfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TranscriptsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Transcripts", name = "transcripts")
    public JAXBElement<TranscriptsType> createTranscripts(TranscriptsType value) {
        return new JAXBElement<TranscriptsType>(_Transcripts_QNAME, TranscriptsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/EmploymentRecord", name = "employmentRecord")
    public JAXBElement<RecordType> createEmploymentRecord(RecordType value) {
        return new JAXBElement<RecordType>(_EmploymentRecord_QNAME, RecordType.class, null, value);
    }

}
